"use client;";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./_components/header";
import Breadcrumb from "./_components/breadcrumb";
import { AuthProvider } from "./_context/auth-context";
import { UserProvider } from "@auth0/nextjs-auth0/client";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <AuthProvider>
          <body className={`${geistSans.variable} ${geistMono.variable}`}>
            <Header />
            <Breadcrumb homeElement="Home" capitalizeLinks />
            {children}
          </body>
        </AuthProvider>
      </UserProvider>
    </html>
  );
}
